### ISSUE TITLE
ipadOS ua for iOS 13 includes 'Macintosh' instead of iPad

### ISSUE THREAD

**Issue by kakarlus** [juliangruber/is-mobile#17]
Just a note

**Comment by juliangruber** [comment]
could you provide a full ios 13 ua string?

**Comment by kakarlus** [comment]
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15

references: 
https://github.com/serbanghita/Mobile-Detect/issues/795
https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct

n.b.
Google Chrome, iOS13 still shows iPad
Safari iOS13 shows Macintosh

**Comment by juliangruber** [comment]
Interesting! Looking at the resources you provided it seems like we can detect it's a tablet through feature detection, but _not_ looking at the user agent string alone, which this module currently does.

**Comment by rikinshah23** [comment]
@kakarlus @juliangruber I am also stuck with same issue but i need to check on Server side so I can show mobile side menu instead of full website menu on Safari iOS13. could you help me with this please? https://stackoverflow.com/questions/58344491/request-browser-ismobiledevice-not-working-with-ipadair2-and-ios-13-0-1

**Comment by juliangruber** [comment]
I think currently you can't, but you could add a header or something that specifies the device

**Comment by kakarlus** [comment]
@rikinshah23 i used something similar to what you did. i checked the `navigator.userAgent`, looked for 'Macintosh' && checked the `navigator.maxTouchPoints`

n.b.
this is to differentiate macbook's user-agent from iPad, because there are no macbooks that are touchscreen **yet**.

**Comment by rikinshah23** [comment]
@kakarlus  yes but that for client side. If I use that in document.ready then it will display menu1 first then it detects the device and then switches the menu2. which does not look nice. I need to display menu2 directly when the page starts to load. Right now server side razor code is not helping (Request.Browser.IsMobileDevice not helping). what should i do? 

@juliangruber how do you mean? How do I add header that specifies the device? where? please explain. thanks both

**Comment by juliangruber** [comment]
> @juliangruber how do you mean? How do I add header that specifies the device? where? please explain. thanks both

If you control how the request is made, eg by using `fetch`, you can send custom headers. If you don't control the request, because it's initiated by the browser, the only idea I have right now is:

1) on page load, run some JS to detect if this is a tablet
2) if it is so, set a cookie on every relevant domain and refresh the page
3) now the backend will be able to tell that this is a tablet from inspecting that cookie

**Comment by archmoj** [comment]
It appears there is a similar problem when using Safari on iPad 7th (13),
in addition to iPad Pro 12.9 (13).

**Comment by archmoj** [comment]
Related: https://stackoverflow.com/questions/58019463/how-to-detect-device-name-in-safari-on-ios-13-while-it-doesnt-show-the-correct
